/** Fixed Lody artifact, never project HTML. One JPEG decode and one pending frame at most. */
export function simulatorViewerHtml(operationId: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#111}body{display:flex;align-items:center;justify-content:center}canvas{max-width:100%;max-height:100%;object-fit:contain;touch-action:none;display:block}</style></head><body><canvas></canvas><script>
'use strict';
const operationId=${JSON.stringify(operationId)};
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');
let parentOrigin,visible=false,ws,pending,decoding=false,generation=0,point,pointer,heartbeat,firstFrame,lastReport;
function report(state){const key=state+':'+canvas.width+':'+canvas.height;if(parentOrigin&&key!==lastReport){lastReport=key;parent.postMessage({type:'lody:ios-simulator:state',operationId,state,width:canvas.width,height:canvas.height},parentOrigin)}}
function send(value){if(ws?.readyState===1)ws.send(JSON.stringify(value))}
function lift(){if(point){send({...point,type:'touch1-up'});point=undefined;pointer=undefined}}
function close(){lift();generation++;clearInterval(heartbeat);clearTimeout(firstFrame);pending=undefined;if(ws){const old=ws;ws=undefined;old.close()}report('disconnected')}
async function draw(){if(decoding)return;decoding=true;try{while(pending){const frame=pending;pending=undefined;const g=generation;try{const image=await createImageBitmap(new Blob([frame],{type:'image/jpeg'}));try{if(g!==generation||!visible)continue;canvas.width=image.width;canvas.height=image.height;ctx.drawImage(image,0,0);clearTimeout(firstFrame);report('ready')}finally{image.close()}}catch{report('error')}}}finally{decoding=false}}
function connect(){if(!visible||document.hidden||ws)return;report('connecting');const url=new URL('stream',location.href);url.protocol=location.protocol==='https:'?'wss:':'ws:';const token=new URL(location.href).searchParams.get('__lody_preview_token');if(token)url.searchParams.set('__lody_preview_token',token);const socket=new WebSocket(url);ws=socket;socket.binaryType='arraybuffer';socket.onopen=()=>{send({type:'heartbeat'});heartbeat=setInterval(()=>{if(visible&&!document.hidden)send({type:'heartbeat'})},15000)};firstFrame=setTimeout(()=>{if(ws===socket){close();report('error')}},20000);socket.onmessage=e=>{if(ws!==socket)return;if(e.data instanceof ArrayBuffer){pending=e.data;void draw()}};socket.onclose=()=>{if(ws===socket){close();report('disconnected')}};socket.onerror=()=>{if(ws===socket){close();report('error')}}}
addEventListener('message',e=>{if(e.source!==parent||e.origin==='null'||!e.data||e.data.operationId!==operationId)return;const d=e.data;if(d.type==='lody:ios-simulator:init'&&!parentOrigin)parentOrigin=e.origin;if(e.origin!==parentOrigin||!['lody:ios-simulator:init','lody:ios-simulator:visibility'].includes(d.type)||typeof d.visible!=='boolean')return;visible=d.visible;if(visible)connect();else close()});
addEventListener('visibilitychange',()=>{if(document.hidden)close();else connect()});addEventListener('pagehide',close);addEventListener('blur',lift);
function position(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height)),width:canvas.width,height:canvas.height}}
canvas.onpointerdown=e=>{if(pointer!==undefined||!canvas.width||ws?.readyState!==1)return;pointer=e.pointerId;point=position(e);canvas.setPointerCapture(pointer);send({...point,type:'touch1-down'});e.preventDefault()};canvas.onpointermove=e=>{if(pointer!==e.pointerId)return;point=position(e);send({...point,type:'touch1-move'})};canvas.onpointerup=e=>{if(pointer===e.pointerId)lift()};canvas.onpointercancel=lift;canvas.onlostpointercapture=lift;
</script></body></html>`;
}
